name: push-hecatoncheires-image

on:
  push:
    branches: [ main ]
    paths:
      - 'images/hecatoncheires/**'
      - '.github/workflows/push-hecatoncheires-image.yml'
      - '.github/workflows/deploy-cloud-run.yml'

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy-cloud-run.yml
    with:
      service_name: hecatoncheires
      image_path: images/hecatoncheires
      project_id: mztn-service
    secrets: inherit
